### PR TITLE
Miscellaneous bug fixes and minor features

### PR DESCRIPTION
**Pull request by josiahjohnston**
- Existing transmission lines now have their sunk costs carried into the objective function. Update example expectations accordingly. Issue #92 
- Ensure that executing `switch solve --help` outside of a project directory will not cause a crash.
- Update outputs of the copperplate0 example (the only example that includes a full set of outputs).
- Have setup.py use the version number from the switch_model package
- Implement `switch --version` for getting the version number from the command-line tool.

### CODE REVIEW

**Comment by josiahjohnston** [comment]
Good catch. I did some digging and changed that to a more robust method similar to what you suggest. Method 3 at https://packaging.python.org/single_source_version/

**Comment by josiahjohnston** [comment]
Can I get a yay or nay so I can close out this branch?

**Comment by mfripp** [comment]
It looks mostly OK. However, I am concerned that you dropped the idea of having a band of capacity that does not participate in the minimum downtime constraint (previously calculated as `committable_fraction`). Without that term, the model can turn off some capacity, and then get around the min-downtime rule by turning on other capacity which is actually forced off by gen_max_commit_fraction, e.g., due to a  maintenance outage.

**Comment by josiahjohnston** [comment]
Ok, I moved the min up/down time futzing to a separate branch and am going to close this one. I was concerned about leaving the transmission sunk costs bug up in the tagged version of the repo for so long. Matthias, can you either push this patched version to PyPi or give me access/show me the ropes so I can do it?

**Pull request merged**
